name:                RuneLink
version:             0.1.0.0
github:              "Isylwin/Haskell_RuneLink"
license:             MIT
author:              "Oscar de Leeuw"
maintainer:          "oscardeleeuw@hotmail.com"
copyright:           "2020 Oscar de Leeuw"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Isylwin/Haskell_RuneLink#readme>

dependencies:
- base >= 4.7 && < 5
- gloss  
- matrix

library:
  source-dirs: src

executables:
  RuneLink-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RuneLink

tests:
  RuneLink-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RuneLink
    - hspec
