name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:          
    - name: Check out
      uses: actions/checkout@v2
         
    - name: Cache stack global package db
      id:   stack-global
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-global-${{ hashFiles('**.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-global

    - name: Cache .stack-work
      uses: actions/cache@v1
      with:
        path: .stack-work
        key: ${{ runner.os }}-stack-work-${{ hashFiles('**.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-work
  
    - name: Install GL dependency
      run: |
        sudo apt-get -y update
        sudo apt-get -y install libglu1-mesa-dev freeglut3-dev mesa-common-dev

    - name: Install GHC
      run: |
        stack setup --install-ghc

    - name: Install Dependencies
      run: |
        stack build --only-dependencies
  
    - name: Build
      run: |
        stack build --fast --ghc-options=-Werror --no-terminal
  
    - name: Run tests
      run: |
        stack test
