name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: mstksg/setup-stack@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.1'
        cabal-version: '2.4'
    - name: Install dependencies
      run: |
        stack setup --install-ghc
    - name: Build
      run: |
        stack build --only-dependencies
    - name: Run tests
      run: |
        stack test
